# Generated by Django 2.1.7 on 2019-02-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirara', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chara',
            name='job',
            field=models.IntegerField(choices=[(0, '戦士'), (1, '魔法使い'), (2, 'ナイト'), (3, '僧侶'), (4, 'アルケミスト')], default=1),
        ),
    ]
